const playlists = {
    "Elisha": [
        { title: "All For Love", author: "Tungevaag, Raaban, Richard Smitt", src: "1 - All For Love.mp3" },
        { title: "Perfect", author: "Ed Sheeran", src: "2 - Perfect.mp3" },
        { title: "Stereo Hearts", author: "Gym Class Heroes, Adam Levine", src: "3 - Stereo Hearts.mp3" },
        { title: "Love Story", author: "Taylor Swift", src: "4 - Love Story.mp3" },
        { title: "Snowman", author: "Sia", src: "5 - Snowman.mp3" },
        { title: "Snowman - Sped Up Version", author: "Sia, sped up nightcore", src: "6 - Snowman - Sped Up Version.mp3" },
        { title: "Numb", author: "Arc North, Aaron Richards, New Beat Order, Cour", src: "7 - Numb.mp3" },
        { title: "Take Me Away", author: "Raaban, Tungevaag, Victor Crone", src: "8 - Take Me Away.mp3" },
        { title: "No More Forever", author: "Alban Chela, Mike Watson", src: "9 - No More Forever.mp3" },
        { title: "Crazy", author: "DJ Goja, Nito-Onna", src: "10 - Crazy.mp3" },
        { title: "ily", author: "MOHA, Irma, Meqq", src: "11 - ily.mp3" },
        { title: "Relax, Take It Easy", author: "UNKLFNKL, dayana", src: "12 - Relax, Take It Easy.mp3" },
        { title: "Apologize", author: "Besomorph, Anthony Keyrouz, Lunis", src: "13 - Apologize.mp3" },
        { title: "The Night Begins to Shine", author: "B.E.R.", src: "14 - The Night Begins to Shine.mp3" },
        { title: "As It Was", author: "Harry Styles", src: "15 - As It Was.mp3" },
        { title: "Dreamer", author: "Marin Hoxha, Ane Flem", src: "16 - Dreamer.mp3" },
        { title: "Never Gonna Give You Up", author: "Rick Astley", src: "17 - Never Gonna Give You Up.mp3" },
        { title: "Until I Found You", author: "Stephen Sanchez", src: "18 - Until I Found You.mp3" },
        { title: "Until I Found You (Sped Up) - Heaven When I Held You Again How Could We Ever Just Be Friends", author: "Hiko", src: "19 - Until I Found You (Sped Up) - Heaven When I Held You Again How Could We Ever Just Be Friends.mp3" },
        { title: "Play", author: "K-391, Alan Walker, Tungevaag, Mangoo", src: "20 - Play.mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
    ],
    "Swifty": [
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
    ],
    "OGs": [
        { title: "", author: "", src: ".mp3" },
        { title: "", author: "", src: ".mp3" },
    ],
};

let currentPlaylist = "Playlist 1";
let currentSongIndex = 0;
let isRepeat = false;

const audio = document.getElementById('audio');
const playlist = document.getElementById('playlist');
const playlistsElement = document.getElementById('playlists');
const search = document.getElementById('search');
const songTitle = document.getElementById('song-title');
const songAuthor = document.getElementById('song-author');
const repeatSwitch = document.getElementById('repeat');

function loadSong(index) {
    const song = playlists[currentPlaylist][index];
    audio.src = song.src;
    audio.play();
    songTitle.textContent = song.title;
    songAuthor.textContent = song.author;
    highlightCurrentSong(index);
}

function highlightCurrentSong(index) {
    const songElements = document.getElementsByClassName('song');
    for (let i = 0; i < songElements.length; i++) {
        songElements[i].classList.remove('current');
    }
    songElements[index].classList.add('current');
}

function createPlaylists() {
    playlistsElement.innerHTML = '';
    for (const playlistName in playlists) {
        const playlistElement = document.createElement('div');
        playlistElement.classList.add('playlist');
        playlistElement.textContent = playlistName;
        playlistElement.addEventListener('click', () => {
            currentPlaylist = playlistName;
            currentSongIndex = 0;
            createPlaylist();
            loadSong(currentSongIndex);
        });
        playlistsElement.appendChild(playlistElement);
    }
}

function createPlaylist() {
    playlist.innerHTML = '';
    playlists[currentPlaylist].forEach((song, index) => {
        const songElement = document.createElement('div');
        songElement.classList.add('song');
        songElement.textContent = `${song.title} - ${song.author}`;
        songElement.addEventListener('click', () => {
            currentSongIndex = index;
            loadSong(index);
        });
        playlist.appendChild(songElement);
    });
}

document.getElementById('prev').addEventListener('click', () => {
    currentSongIndex = (currentSongIndex > 0) ? currentSongIndex - 1 : playlists[currentPlaylist].length - 1;
    loadSong(currentSongIndex);
});

document.getElementById('next').addEventListener('click', () => {
    currentSongIndex = (currentSongIndex < playlists[currentPlaylist].length - 1) ? currentSongIndex + 1 : 0;
    loadSong(currentSongIndex);
});

document.getElementById('backward').addEventListener('click', () => {
    audio.currentTime = Math.max(0, audio.currentTime - 10);
});

document.getElementById('forward').addEventListener('click', () => {
    audio.currentTime = Math.min(audio.duration, audio.currentTime + 10);
});

search.addEventListener('input', () => {
    const query = search.value.toLowerCase();
    let filteredSongs = [];
    for (const playlistName in playlists) {
        playlists[playlistName].forEach((song) => {
            if (song.title.toLowerCase().includes(query) || song.author.toLowerCase().includes(query)) {
                filteredSongs.push({ ...song, playlistName });
            }
        });
    }
    playlist.innerHTML = '';
    filteredSongs.forEach((song, index) => {
        const songElement = document.createElement('div');
        songElement.classList.add('song');
        songElement.textContent = `${song.title} - ${song.author} (${song.playlistName})`;
        songElement.addEventListener('click', () => {
            currentPlaylist = song.playlistName;
            currentSongIndex = playlists[currentPlaylist].findIndex(s => s.src === song.src);
            loadSong(currentSongIndex);
        });
        playlist.appendChild(songElement);
    });
});

audio.addEventListener('ended', () => {
    if (isRepeat) {
        loadSong(currentSongIndex);
    } else {
        currentSongIndex = (currentSongIndex < playlists[currentPlaylist].length - 1) ? currentSongIndex + 1 : 0;
        loadSong(currentSongIndex);
    }
});

repeatSwitch.addEventListener('change', () => {
    isRepeat = repeatSwitch.checked;
});

createPlaylists();
createPlaylist();
loadSong(currentSongIndex);