name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Suppress build step
        run: |
          echo "No build step to run" > /dev/null 2>&1

      - name: Suppress test step
        run: |
          echo "No test step to run" > /dev/null 2>&1

      - name: Clean up (silent)
        run: |
          echo "Cleaning up..." > /dev/null 2>&1
          rm -rf build > /dev/null 2>&1 || true
          echo "Clean up complete." > /dev/null 2>&1
